name: Deploy API to VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /www/wwwroot/balapasa
            git pull origin master
            npm install
            npx prisma db push --accept-data-loss
            npx prisma generate
            npm run build
            pm2 restart balapasa
